[package]
name = "example"
version = "0.0.1"
license = "MIT"
edition = "2024"
publish = false

[dependencies]
esp-hal = { version = "*", features = ["esp32s3", "unstable"] }
esp-bootloader-esp-idf = { version = "*", features = ["esp32s3"] }
esp-alloc = "*"
# critical-section = "*"

embedded-hal = "*"
embedded-hal-bus = "*"
embedded-hal-async = "*"
# static_cell = "*"

epd-ssd1680 = { path = ".." }
display-interface-spi = "*"
embedded-graphics = "*"

[features]
default = ["log"]
# use log for logging
log = ["epd-ssd1680/log"]
# use dfmt for logging
defmt = ["epd-ssd1680/defmt"]

# use async SPI
async = [
    "embedded-hal-bus/async",
    "epd-ssd1680/async"
]


# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = "s"

[profile.release]
codegen-units = 1 # LLVM can perform better optimizations using a single thread
debug = 2         # prefer slower builds but better debugging experience
lto = 'fat'
opt-level = 's'
